### ISSUE TITLE
batch script to detect vague festivals that actually have a precise counterpart

### ISSUE THREAD

**Issue by ruettet** [Kunstenpunt/havelovewilltravel#344]
bijvoorbeeld
![image](https://user-images.githubusercontent.com/1922425/99061678-3475d800-25a2-11eb-8370-33102159e075.png)

of

![image](https://user-images.githubusercontent.com/1922425/99061762-52dbd380-25a2-11eb-9f57-169e148181f5.png)

**Comment by ruettet** [comment]
een vergelijkbaar script staat hier:
https://github.com/Kunstenpunt/havelovewilltravel/blob/master/hlwtadmin/management/commands/clean_duplicated_relations.py

**Comment by ruettet** [comment]
de voorzet van dirk https://github.com/Kunstenpunt/havelovewilltravel/blob/master/hlwtadmin/management/commands/merge_more_vaguely_dated_counterparts_of_existing_concerts.py kan efficienter, denk ik: kan dat niet een pak efficienter als je enkel itereert door concerten met een "until_date is not None", en dan voor elk van die concerten een concert zoekt met een specifieke datum binnen de begin en end van het initiele concert (+ zelfde artiest + zelfde organisatie)? Da's een veel kleinere search space, toch? In principe heb je dan in 1 pass niet alles opgelost, maar het is een recurrent bash script, dus bij een tweede run heb je de overblijvende vage concerten, en bij een derde run de nog overblijvende

**Comment by ddehertog** [comment]
Langs de andere kant, dit loopt een enkele keer en vindt alles. Maakt het uit dat dit een half uur loopt 's nachts?Op 10 mrt. 2021 14:22 schreef "Tom R." ***@***.***>:
de voorzet van dirk https://github.com/Kunstenpunt/havelovewilltravel/blob/master/hlwtadmin/management/commands/merge_more_vaguely_dated_counterparts_of_existing_concerts.py kan efficienter, denk ik: kan dat niet een pak efficienter als je enkel itereert door concerten met een "until_date is not None", en dan voor elk van die concerten een concert zoekt met een specifieke datum binnen de begin en end van het initiele concert (+ zelfde artiest + zelfde organisatie)? Da's een veel kleinere search space, toch? In principe heb je dan in 1 pass niet alles opgelost, maar het is een recurrent bash script, dus bij een tweede run heb je de overblijvende vage concerten, en bij een derde run de nog overblijvende
